name: 'Generate coreserver'
description: 'Generate deployment files for coreserver'
inputs:
  topdomain:
    description: 'Top domain to generate files for'
    required: true
    default: ''
  apikey:
    description: 'API key for the domain'
    required: true
    default: ''
  token:
    description: 'Github token'
    required: true
    default: ''
runs:
  using: 'composite'
  # main: 'dist/index.js'
  steps:
    - name: Generate files
      shell: bash
      run: | 
        node ${{github.action_path}}/dist/index.js
      env:
        INPUT_TOPDOMAIN: ${{ inputs.topdomain }}
        INPUT_APIKEY: ${{ inputs.apikey }}
        INPUT_TOKEN: ${{ inputs.token }}

    - name: Checkout deployment
      uses: actions/checkout@v4
      with:
        repository: Sysarb/k8s-deployments
        token: ${{ inputs.token }}
        path: deployments

    - name: Remove existing files
      shell: bash
      run: |
        rm -rf ${{github.workspace}}/deployments/coreserver/${{ inputs.topdomain }}

    - name: Copy new files
      shell: bash
      run: |
        cp -r ${{github.action_path}}/dist/${{ inputs.topdomain }} ${{github.workspace}}/deployments/coreserver/
    
    - name: Commit changes
      shell: bash
      run: |
          cd deployments
          git config --global user.email "devops@sysarb.se"
          git config --global user.name "Sysarb"
          git add .
          git commit -m "Generate coreserver ${{ inputs.version }}"
          git push
